INSERT INTO CARS(CAR_ID, CAR_BRAND, CAR_COLOR, CAR_MODEL, CAR_YEAR)VALUES ('1','Audi','Black','Etron','2020');
INSERT INTO CARS(CAR_ID, CAR_BRAND, CAR_COLOR, CAR_MODEL, CAR_YEAR)VALUES ('2','Audi','Black','Q7','2020');
INSERT INTO FACTORYS VALUES('1','Wolfsburg','Germany','Volkswagen','38440 Wolfsburg','38440')